### ISSUE TITLE
NodeJs v8 stream.push() after EOF

### ISSUE THREAD

**Issue by Eldar-X** [koajs/compress#60] opened 2017-05-31 18:27 UTC
After upgrade to v8 i got error in console

` Error: stream.push() after EOF
      at readableAddChunk (_stream_readable.js:227:30)
      at Gzip.Readable.push (_stream_readable.js:195:10)
      at Gzip.Transform.push (_stream_transform.js:151:32)
      at Zlib.callback (zlib.js:430:16)`

**Comment by tuananh** [comment] 2017-06-02 02:05
Confirmed. I get this issue with Node v8 as well.

**Comment by tuananh** [comment] 2017-06-08 12:37
Anyone taking this? Can someone point me to where I should look?

**Comment by tuananh** [comment] 2017-06-08 22:23
Notice node 8.1 fixes something in zlib. Is this related?

> A regression in the Zlib module that made it impossible to properly subclasses zlib.Deflate and other Zlib classes has been fixed. [6aeb555cc4] #13374.

**Comment by andykant** [comment] 2017-06-09 17:10
This still occurs in Node v8.1.0.

**Comment by niftylettuce** [comment] 2017-06-09 20:51
Same issue, v8.0.0

**Comment by tuananh** [comment] 2017-06-13 13:53
@jonathanong could you please take a look?

**Comment by jonathanong** [comment] 2017-06-13 17:59
i've seen this before. i haven't investigated it yet. it is one of the blockers for me to upgrading to node 8.

**Comment by tuananh** [comment] 2017-06-20 13:07
anyone found a fix for this? also, is there an alternative middleware?

**Comment by Eldar-X** [comment] 2017-06-20 16:10
In my case, i found solution by changing order of compress and conditional-get middleware
```
    app.use(compress({
      flush: require('zlib').Z_SYNC_FLUSH
    }))
    .use(conditional())
    .use(etag())
```

**Comment by jonathanong** [comment] 2017-06-20 16:41
is it because you are using `Z_SYNC_FLUSH`? what happens if you don't use a flush parameter?

**Comment by jonathanong** [comment] 2017-06-20 17:04
https://github.com/koajs/compress/commit/e50d15f4941791e3b425fc7a218282effedc652a seems okay to me. 

anyone else have any ideas?

**Comment by Eldar-X** [comment] 2017-06-20 17:37
@jonathanong without flush parameter i have same result but if koa-compress middleware over conditional-get middleware everything okay. Looks like this issue happening only when we use conditional-get middleware.

**Comment by jonathanong** [comment] 2017-06-21 03:57
okay, i think the time i saw this error was with `v8.0.0`. i don't see it anymore with the latest node

**Comment by tuananh** [comment] 2017-06-21 04:14
It seems 8.1.2 fixes it. Any idea what causes this in the first place?

**Comment by pastelsky** [comment] 2017-06-21 04:30
Still experiencing this in 8.1.2. I don't have `conditional-get` middleware.

**Comment by Eldar-X** [comment] 2017-06-21 16:38
I have same issue in 8.1.2 but with conditional-get middleware. I see this issue once more when my stream was broken.

**Comment by jonathanong** [comment] 2017-06-21 17:00
can anyone make a PR with a failing test casE?

**Comment by tuananh** [comment] 2017-06-22 01:51
this? https://github.com/nodejs/node/issues/13812

there is a PR open already for it https://github.com/nodejs/node/pull/13850

**Comment by tuananh** [comment] 2017-06-22 15:31
```
const rs = new Stream.Readable()
rs.push(null)
rs.push('ok')
rs._read = () => {}
ctx.body = rs
```

This test is failing with the same error. though i don't know why.

**Comment by mcollina** [comment] 2017-06-22 15:32
Can you check if https://github.com/nodejs/node/pull/13850 this solves the issue?

**Comment by andykant** [comment] 2017-07-06 05:11
Node 8.1.3 fixes the issue.

**Comment by tuananh** [comment] 2017-07-06 05:20
8.1.3 works for me as well

**Comment by jonathanong** [comment] 2017-07-06 17:10
closing. thanks @mcollina !

**Closed by jonathanong** 2017-07-06 17:10 UTC

**Comment by Eldar-X** [comment] 2017-07-10 09:15
node v8.1.3 still same issue

```const Koa = require('koa');
const app = new Koa();

const conditional = require('koa-conditional-get');
const etag = require('koa-etag');
const compress = require('koa-compress');
const serveStatic = require('koa-static');

app.use(conditional())
app.use(etag())
app.use(compress())
app.use(serveStatic('public'))

app.use(async(ctx, next) => {
  ctx.type = 'text/html';
  ctx.body = `<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/test.css">
  </head>
  <body>
  Response OK
  </body>
  </html>`;
})

app.listen(3000)
```

**Comment by mrchief** [comment] 2017-07-12 15:38
I don't use conditional get or etag and still see this issue (with node 8.1.3 and even using Z_SYNC_FLUSH). I'm using koa-webpack middleware though.

**Comment by mcollina** [comment] 2017-07-12 17:39
I'll be happy to have a look, if you can post an example to reproduce the issue consistently.

**Comment by Eldar-X** [comment] 2017-07-12 19:20
@mcollina you can try my example only install deps and run this app then visit page and reload it! After reloading you can see this message in your console

2. I am using Marko.js and i streaming response to ctx.body but if i have error in my template file i also see this error message.

**Comment by mrchief** [comment] 2017-07-12 21:09
@mcollina My setup is bit complicated but @Eldar-X setup will do.

**Comment by mcollina** [comment] 2017-07-13 08:10
@Eldar-X @mrchief I cannot reproduce with node 8.1.2, 8.1.3, 8.1.4 or master using your example on Mac OS X 10.11 and Chrome.

**Comment by mrchief** [comment] 2017-07-13 17:09
Could the OS be a factor? I'm on Windows 7 x64. Even in my setup, I don't get it consistently. E.g., I ran my app right now and there were no errors. Then I refreshed the page and saw this error. And sometimes it happens many times within the same request.

I'll try to upload my setup tonight.

**Comment by Eldar-X** [comment] 2017-07-13 17:19
@mcollina i am also on Mac Os 10.11 

![tem-13-2017 20-17-07](https://user-images.githubusercontent.com/15696752/28178780-530a9608-6808-11e7-9f11-4878bd4456fa.gif)

**Comment by Eldar-X** [comment] 2017-07-13 17:25
https://github.com/Eldar-X/koa-issue my simple setup

**Comment by mcollina** [comment] 2017-07-13 17:34
Confirmed, this is still happening. Quite interestly enough, this does not happen with CURL. I'll see if I can track this down (it might take a while).

It seems a different one than https://github.com/nodejs/node/pull/13850.

**Comment by mcollina** [comment] 2017-07-17 16:53
Now I cannot reproduce anymore. However, the same node version/code was showing the problem while I was traveling (and I could not work on it). If someone has a consistent way of reproducing this problem, please let me know.

**Comment by mcollina** [comment] 2017-07-17 17:28
I can reproduce by loading the server with autocannon:

```
autocannon -H Accept-Encoding=gzip -c 100 -d 5 localhost:3000
```

**Comment by mcollina** [comment] 2017-07-17 17:41
Here is the fix: https://github.com/nodejs/node/pull/14330

**Comment by refack** [comment] 2017-07-19 12:54
Will you be adding a regression test for this? Then maybe [apply for addition to node's CitGM](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm)

**Comment by mcollina** [comment] 2017-07-20 22:55
This should be definitely fixed in Node 8.2.1.

**Comment by refack** [comment] 2017-07-21 19:34
@jonathanong if you could write a regression test for this. It's literally keeping up at night 😨

**Comment by jonathanong** [comment] 2017-07-22 18:19
@refack im not sure what the test case is...

**Comment by refack** [comment] 2017-07-22 18:21
@jonathanong this might help https://github.com/nodejs/node/pull/14330/files 🤷‍♂️

**Comment by DominicTobias** [comment] 2018-03-14 09:08
I have it on 8.10.0 on windows

**Comment by mcollina** [comment] 2018-03-14 09:30
@DominicTobias can you please confirm that https://github.com/koajs/compress/issues/60#issuecomment-314051059 can be used to reproduce the problem?

**Comment by DominicTobias** [comment] 2018-03-14 09:32
Ah don't worry, I speed read on a number of issues and this is a general problem with npm and windows, rather than something koa specific 😳

**Comment by khaledAltuwaijri** [comment] 2018-05-09 22:43
(after upgrading node to v8.11.1)
```
$ npm doctor 
npm ERR! stream.push() after EOF
```

**Comment by dandradesg** [comment] 2018-07-17 15:40
npm cache clean --force

**Comment by rimiti** [comment] 2018-07-18 16:05
In my case, after making a `npm cache clean --force`, everything work.
